### PR TITLE
Better support for selfHosted and SSL connections

### LINKED ISSUE #92: x509: certificate signed by unknown authority
time="2023-04-15T09:59:48Z" level=debug msg="image is not latest docker.io/istio/proxyv2: 1.11.4 -> 1.17.2" container=istio-proxy module=controller
name=tst-gh-int82-xfr-dispatch-656c66454-tj47x namespace=tst-gh
time="2023-04-15T09:59:48Z" level=error msg="error syncing 'tst-gh-int82-xfr-dispatch-656c66454-tj47x/tst-gh':
failed to sync pod tst-gh-int82-xfr-dispatch-656c66454-tj47x/tst-gh: failed to check container image "int82-xfr-dispatch":
failed to get tags from remote registry for "ol8-tst-k8s-master-node.com:5000/int82-xfr-dispatch": failed to get docker image:
Get "[https://ol8-tst-k8s-master-node.gcp.itemate.com:5000/v2/int82-xfr-dispatch/tags/list?n=500\](https://ol8-tst-k8s-master-node.gcp.itemate.com:5000/v2/int82-xfr-dispatch/tags/list?n=500%5C)": x509: certificate signed by unknown authority,
requeuing" module=controller

curl -k -u docker_reg:0IFmcttx00 https://ol8-tst-k8s-master-node.com:5000/v2/int82-xfr-dispatch/tags/list?n=5000
{"name":"int82-xfr-dispatch","tags":["tst-bj-20211102-J11-237-1183f99c","tst-gh-20211117-J13-240-c3f64612"

   version-checker
Args:
  --test-all-containers
  --selfhosted-username=docker_reg
  --selfhosted-password=0IFmcttx00
  --insecure-skip-tls-verify=true
  --log-level=debug
This is the Error that I am getting in the log file.
How are you calling the versions. What do I need to add to my config
I would seem that the x509 error could be from an incorrect certificate. Not sure which certificate could be incorrect as I do not understand how you are calling the Get https://

### PR DESCRIPTION
**Pull request by davidcollom**
Closes #92 and #72  - to be clear this is **NOT** a solution, only a work around, for the time being.

### CODE REVIEW

File: pkg/client/selfhosted/selfhosted.go [hunk 1]
```diff
@@ -270,3 +277,24 @@ func (c *Client) setupBasicAuth(ctx context.Context, url string) (string, error)
...
+
+func newTLSConfig(insecure bool, CAPath string) (*tls.Config, error) {
+	// Load system CA Certs and/or create a new CertPool
+	rootCAs, _ := x509.SystemCertPool()
+	if rootCAs == nil {
+		rootCAs = x509.NewCertPool()
+	}
+
+	if CAPath != "" {
+		certs, err := ioutil.ReadFile(CAPath)
```
Comment (ChaosInTheCRD) [inline pkg/client/selfhosted/selfhosted.go:289]: The only thing that springs to mind here is how this RootCA could be rotated. Maybe this is "fine" for now? we might want to consider https://github.com/dyson/certman to ensure the tls config changes when the file does.
