### PR TITLE
ghcr.io: List packages based on whether owner is an org or a user

### LINKED ISSUE #179: Cannot check packages stored on the Github Container Registry
Hello there! I'm having an issue with VC being unable to get tags from the GHCR:

```
time="2024-04-15T19:52:26Z" level=error msg="error syncing 'radarr-698cdfdc65-5gs6r/servarr': failed to sync pod radarr-698cdfdc65-5gs6r/servarr: failed to check container image \"postgres-init\": failed to get tags from remote registry for \"ghcr.io/onedr0p/postgres-init\": failed to get Org Package Versions: GET https://api.github.com/orgs/onedr0p/packages/container/postgres-init/versions?package_type=container&per_page=100&state=active: 404 Not Found [], requeuing" module=controller
```

I am using a github token but didn't select any scopes because none of them seemed relevant. This might possibly be related to issue #175?

Thanks!

### PR DESCRIPTION
**Pull request by ribbybibby**
We were previously using releases to figure out tags for a Github package. I think this was wrong. Not all release tags will be pushed as package versions, and vice versa. Someone may choose to use GHCR without taking advantage of releases at all.

I've modified it so that the client will check if the owner is a user or an org and then make the appropriate `PackageGetAllVersions` function call to retrieve the tags.

I've also fixed a few other things I ran into while testing this:
1. Create the github client in `New` so that rate limiting and other goodness is reused across calls.
2. Fix `RepoImageFromPath`, so it will split the repository path into the 'owner' and 'repo' segments that `Tags` expects. Previously we would have got errors for subrepositories.
3. Update `TestRepoImage` to ensure it doesn't panic on unexpected inputs.
4. We don't need to use regex to match `ghcr.io` to `ghcr.io`.
5. If we're excluding `.att` tags then we should probably exclude `.sig` and `.sbom` too.

Fixes #179, #175

### CODE REVIEW

File: pkg/client/ghcr/ghcr.go [hunk 1]
```diff
@@ -47,42 +29,47 @@ func (c *Client) Tags(ctx context.Context, host, owner, repo string) ([]api.Imag
...
 
-func getTagsFromOrgPackage(client *github.Client, owner string, repo string) ([]api.ImageTag, error) {
-	var tags []api.ImageTag
-	packageType := "container"
-	packageState := "active"
+func (c *Client) Tags(ctx context.Context, host, owner, repo string) ([]api.ImageTag, error) {
+	// Choose the correct list packages function based on whether the owner
+	// is a user or an organization
+	getAllVersions := c.client.Organizations.PackageGetAllVersions
+	user, _, err := c.client.Users.Get(ctx, owner)
```
Comment (davidcollom) [inline pkg/client/ghcr/ghcr.go:47]: GitHub has a very aggressive rate limit - we should look to try and cache this somewhere/where possible as this could cause image discovery to be significantly delayed or fail.

File: pkg/client/ghcr/ghcr.go [hunk 2]
```diff
@@ -110,35 +104,9 @@ func getTagsFromOrgPackage(client *github.Client, owner string, repo string) ([]
 		if resp.NextPage == 0 {
 			break
 		}
+
 		opts.ListOptions.Page = resp.NextPage
 	}
-	return tags, nil
-}
 
-func getTagsFromRelease(client *github.Client, owner string, repo string) ([]api.ImageTag, error) {
```
Comment (davidcollom) [inline pkg/client/ghcr/ghcr.go:118]: Using releases, was a way of being significantly quicker than searching the repo due to GitHubs aggressive rate limiting... Maybe this could be an option/annotation perhaps to enable/disable or a fallback?

File: pkg/client/ghcr/path.go [hunk 3]
```diff
@@ -1,20 +1,21 @@
...
 )
 
-var (
-	reg = regexp.MustCompile(`^ghcr.io$`)
-)
-
 func (c *Client) IsHost(host string) bool {
-	return reg.MatchString(host)
+	return host == "ghcr.io"
 }
```
Comment (davidcollom) [inline pkg/client/ghcr/path.go:9]: I get that this makes it simpler, but does make it harder or more complex if github decide to add additional subdomains etc or even their domain (not sure they would) additionally this does some what diverge the logic from other clients.

Comment (ribbybibby) [reply pkg/client/ghcr/path.go:9]: I don't think the fact that we might need a regex down the line is a good reason to use a regex unnecessarily here. If GHCR starts using different domains, we could introduce a regex when that happens. We'd have to update the code either way in that situation.

I also don't think the implementation matching how things are done in other clients has much benefit either. As long as the interface is satisfied, I think the details of the implementation should be the simplest possible.

That being said, I just made this change in passing and it isn't really related to the PR, so happy to revert. It's more of a style thing than anything else.

File: pkg/client/ghcr/ghcr.go (hunk 2 above)
Comment (ribbybibby) [reply pkg/client/ghcr/ghcr.go:118]: Being able to say 'I want to use release versions to figure out latest' for specific repositories sounds like a good feature. We probably need to think about the best way to do that.

I would say that we could merge this PR, which fixes things for repositories that are currently broken, and then think about that in a follow up?

File: pkg/client/ghcr/ghcr.go (hunk 1 above)
Comment (ribbybibby) [reply pkg/client/ghcr/ghcr.go]: Addressed in efb6cc44b9ed2b5ee0fe173f4873e8aa72a2a826.

File: pkg/client/ghcr/ghcr.go (hunk 2 above)
Comment (davidcollom) [reply pkg/client/ghcr/ghcr.go:118]: I'm happy to merge if an Issue is raised to capture this? (Once I get time to re-review things 🙈 )

File: pkg/client/ghcr/path.go (hunk 3 above)
Comment (hawksight) [reply pkg/client/ghcr/path.go:9]: To a Go newby like me the newer version is easier to understand in the context of the file it is in.
I agree, if GitHub adds new domains, we'll likely want an issue and code change down the line anyway.

File: pkg/client/ghcr/ghcr.go (hunk 2 above)
Comment (hawksight) [reply pkg/client/ghcr/ghcr.go:118]: Issue raised #196 to cover this, primarily to unblock this PR :)

**Comment by hawksight** [comment]
Appreciate the contextual description at the top of the PR @ribbybibby. I've added issue / thoughts on the existing comments. I think it'd be good to merge and fix for users of ghcr.io.

@davidcollom I'll defer to you for approval. My Go isn't good enough to properly review. But from a "this is what the PR tackles" perspective I give it 👍

**Review by davidcollom — APPROVED** [review]
Thanks @ribbybibby for this! 👍  Sorry its taken some time, but I needed/wanted to verify a few usecases I've seen in the passed with ghcr... but I didn't have a cluster on hand that I could use to verify.

I've done this now and everything looked/worked perfectly 👌  Thanks!

**Review by davidcollom — APPROVED** [review]
